package dev.example.moodlenative.runtime

import dev.example.moodlenative.core.LmsAssignmentItem
import dev.example.moodlenative.data.CalendarPreferencesForm
import dev.example.moodlenative.data.LiveAssignmentDetailResult
import dev.example.moodlenative.data.LiveCalendarResult
import dev.example.moodlenative.data.LiveDashboardResult
import dev.example.moodlenative.data.LiveForumResult
import dev.example.moodlenative.features.MessagePreferencesPresentation
import dev.example.moodlenative.features.NotificationPreferencesPresentation
import dev.example.moodlenative.presentation.AppSessionPresentationState
import dev.example.moodlenative.presentation.AppUiState
import dev.example.moodlenative.storage.AppSessionSnapshot

internal fun AppUiState.Companion.create(
    sessionSnapshot: AppSessionSnapshot = AppSessionSnapshot(),
    liveDashboardResult: LiveDashboardResult? = null,
    isLoadingLiveDashboard: Boolean = false,
    sessionActionMessage: String? = null,
    selectedAssignment: LmsAssignmentItem? = null,
    liveAssignmentDetailResult: LiveAssignmentDetailResult? = null,
    isLoadingAssignmentDetail: Boolean = false,
    assignmentActionMessage: String? = null,
    isUpdatingAssignmentAction: Boolean = false,
    forumIDText: String = "",
    liveForumResult: LiveForumResult? = null,
    isLoadingForum: Boolean = false,
    forumActionMessage: String? = null,
    isUpdatingForumAction: Boolean = false,
    notificationActionMessage: String? = null,
    isUpdatingNotifications: Boolean = false,
    notificationPreferencesPresentation: NotificationPreferencesPresentation? = null,
    isLoadingNotificationPreferences: Boolean = false,
    isUpdatingNotificationPreferences: Boolean = false,
    notificationPreferencesMessage: String? = null,
    messagePreferencesPresentation: MessagePreferencesPresentation? = null,
    isLoadingMessagePreferences: Boolean = false,
    isUpdatingMessagePreferences: Boolean = false,
    messagePreferencesMessage: String? = null,
    courseActionMessage: String? = null,
    isUpdatingCourseFavorite: Boolean = false,
    calendarPreferencesForm: CalendarPreferencesForm = CalendarPreferencesForm(),
    isLoadingCalendarPreferences: Boolean = false,
    isUpdatingCalendarPreferences: Boolean = false,
    calendarPreferencesMessage: String? = null,
    liveCalendarResult: LiveCalendarResult? = null,
    isLoadingCalendarSubscription: Boolean = false,
): AppUiState =
    create(
        session = resolveSessionPresentationState(
            sessionSnapshot = sessionSnapshot,
            liveDashboardResult = liveDashboardResult,
            liveForumResult = liveForumResult,
            liveCalendarResult = liveCalendarResult,
        ),
        liveDashboardResult = liveDashboardResult,
        isLoadingLiveDashboard = isLoadingLiveDashboard,
        sessionActionMessage = sessionActionMessage,
        selectedAssignment = selectedAssignment,
        liveAssignmentDetailResult = liveAssignmentDetailResult,
        isLoadingAssignmentDetail = isLoadingAssignmentDetail,
        assignmentActionMessage = assignmentActionMessage,
        isUpdatingAssignmentAction = isUpdatingAssignmentAction,
        forumIDText = forumIDText,
        liveForumResult = liveForumResult,
        isLoadingForum = isLoadingForum,
        forumActionMessage = forumActionMessage,
        isUpdatingForumAction = isUpdatingForumAction,
        notificationActionMessage = notificationActionMessage,
        isUpdatingNotifications = isUpdatingNotifications,
        notificationPreferencesPresentation = notificationPreferencesPresentation,
        isLoadingNotificationPreferences = isLoadingNotificationPreferences,
        isUpdatingNotificationPreferences = isUpdatingNotificationPreferences,
        notificationPreferencesMessage = notificationPreferencesMessage,
        messagePreferencesPresentation = messagePreferencesPresentation,
        isLoadingMessagePreferences = isLoadingMessagePreferences,
        isUpdatingMessagePreferences = isUpdatingMessagePreferences,
        messagePreferencesMessage = messagePreferencesMessage,
        courseActionMessage = courseActionMessage,
        isUpdatingCourseFavorite = isUpdatingCourseFavorite,
        calendarPreferencesForm = calendarPreferencesForm,
        isLoadingCalendarPreferences = isLoadingCalendarPreferences,
        isUpdatingCalendarPreferences = isUpdatingCalendarPreferences,
        calendarPreferencesMessage = calendarPreferencesMessage,
        liveCalendarResult = liveCalendarResult,
        isLoadingCalendarSubscription = isLoadingCalendarSubscription,
    )

internal fun AppUiState.Companion.create(
    session: AppSessionPresentationState = AppSessionPresentationState(),
    liveDashboardResult: LiveDashboardResult? = null,
    isLoadingLiveDashboard: Boolean = false,
    sessionActionMessage: String? = null,
    selectedAssignment: LmsAssignmentItem? = null,
    liveAssignmentDetailResult: LiveAssignmentDetailResult? = null,
    isLoadingAssignmentDetail: Boolean = false,
    assignmentActionMessage: String? = null,
    isUpdatingAssignmentAction: Boolean = false,
    forumIDText: String = "",
    liveForumResult: LiveForumResult? = null,
    isLoadingForum: Boolean = false,
    forumActionMessage: String? = null,
    isUpdatingForumAction: Boolean = false,
    notificationActionMessage: String? = null,
    isUpdatingNotifications: Boolean = false,
    notificationPreferencesPresentation: NotificationPreferencesPresentation? = null,
    isLoadingNotificationPreferences: Boolean = false,
    isUpdatingNotificationPreferences: Boolean = false,
    notificationPreferencesMessage: String? = null,
    messagePreferencesPresentation: MessagePreferencesPresentation? = null,
    isLoadingMessagePreferences: Boolean = false,
    isUpdatingMessagePreferences: Boolean = false,
    messagePreferencesMessage: String? = null,
    courseActionMessage: String? = null,
    isUpdatingCourseFavorite: Boolean = false,
    calendarPreferencesForm: CalendarPreferencesForm = CalendarPreferencesForm(),
    isLoadingCalendarPreferences: Boolean = false,
    isUpdatingCalendarPreferences: Boolean = false,
    calendarPreferencesMessage: String? = null,
    liveCalendarResult: LiveCalendarResult? = null,
    isLoadingCalendarSubscription: Boolean = false,
): AppUiState {
    val dashboard = resolveDashboardPresentation(liveDashboardResult)
    val assignmentDetail = resolveAssignmentDetailPresentation(
        selectedAssignment = selectedAssignment,
        liveAssignmentDetailResult = liveAssignmentDetailResult,
    )
    val forum = resolveForumPresentation(
        forumIDText = forumIDText,
        liveForumResult = liveForumResult,
        isLoadingForum = isLoadingForum,
    )
    val calendarSubscription = resolveCalendarSubscriptionPresentation(liveCalendarResult)

    return AppUiState(
        session = session,
        now = dashboard.now,
        zoneId = dashboard.zoneId,
        courses = dashboard.courses,
        assignments = dashboard.assignments,
        notifications = dashboard.notifications,
        selectedAssignment = selectedAssignment,
        assignmentDetailPresentation = assignmentDetail.presentation,
        assignmentDetailStatusRows = assignmentDetail.statusRows,
        isLoadingAssignmentDetail = isLoadingAssignmentDetail,
        assignmentActionMessage = assignmentActionMessage,
        isUpdatingAssignmentAction = isUpdatingAssignmentAction,
        forumIDText = forumIDText,
        forumDiscussions = forum.discussions,
        forumSelectedDiscussion = forum.selectedDiscussion,
        forumPostThreads = forum.postThreads,
        forumPartialErrors = forum.partialErrors,
        forumError = forum.error,
        forumPrimaryLabel = forum.primaryLabel,
        forumStatusLabel = forum.statusLabel,
        isLoadingForum = isLoadingForum,
        forumActionMessage = forumActionMessage,
        isUpdatingForumAction = isUpdatingForumAction,
        isLoadingLiveDashboard = isLoadingLiveDashboard,
        loadedAt = dashboard.loadedAt,
        dashboardError = dashboard.error,
        unreadNotificationCount = dashboard.unreadNotificationCount,
        notificationActionMessage = notificationActionMessage,
        isUpdatingNotifications = isUpdatingNotifications,
        notificationPreferencesPresentation = notificationPreferencesPresentation,
        isLoadingNotificationPreferences = isLoadingNotificationPreferences,
        isUpdatingNotificationPreferences = isUpdatingNotificationPreferences,
        notificationPreferencesMessage = notificationPreferencesMessage,
        messagePreferencesPresentation = messagePreferencesPresentation,
        isLoadingMessagePreferences = isLoadingMessagePreferences,
        isUpdatingMessagePreferences = isUpdatingMessagePreferences,
        messagePreferencesMessage = messagePreferencesMessage,
        courseActionMessage = courseActionMessage,
        isUpdatingCourseFavorite = isUpdatingCourseFavorite,
        calendarPreferencesForm = calendarPreferencesForm.toPresentationForm(),
        isLoadingCalendarPreferences = isLoadingCalendarPreferences,
        isUpdatingCalendarPreferences = isUpdatingCalendarPreferences,
        calendarPreferencesMessage = calendarPreferencesMessage,
        calendarSubscription = calendarSubscription.subscription,
        calendarStatusMessage = calendarSubscription.statusMessage,
        isLoadingCalendarSubscription = isLoadingCalendarSubscription,
        partialErrors = dashboard.partialErrors,
        sessionActionMessage = sessionActionMessage,
    )
}
